# ---- Builder Stage ----
# Use a Node.js version that matches your development environment (e.g., LTS)
FROM node:20-slim AS builder

# Install OpenSSL, which Prisma needs for downloading its engines
RUN apt-get update -y && \
    apt-get install -y openssl && \
    rm -rf /var/lib/apt/lists/* # Clean up apt cache

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY prisma ./prisma/
RUN npx prisma generate
COPY . .
RUN npm run build

# ---- Runtime Stage ----
# FROM node:20-alpine AS runtime # <-- Change this line
FROM node:20-slim AS runtime     

WORKDIR /usr/src/app
ENV NODE_ENV production
COPY package*.json ./
RUN npm install --omit=dev
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/prisma ./prisma
COPY --from=builder /usr/src/app/node_modules/.prisma ./node_modules/.prisma
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh
EXPOSE 3000
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
CMD ["node", "dist/src/bootstrap.js"]